// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Chatgpt35TurboConversationLog is the predicate function for chatgpt35turboconversationlog builders.
type Chatgpt35TurboConversationLog func(*sql.Selector)

// Conversations is the predicate function for conversations builders.
type Conversations func(*sql.Selector)

// TwitterAccounts is the predicate function for twitteraccounts builders.
type TwitterAccounts func(*sql.Selector)
