// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/YukiTsuchida/conversational-ai-sns-bot/app/controller/ent/conversations"
	"github.com/YukiTsuchida/conversational-ai-sns-bot/app/controller/ent/predicate"
	"github.com/YukiTsuchida/conversational-ai-sns-bot/app/controller/ent/twitteraccounts"
)

// TwitterAccountsQuery is the builder for querying TwitterAccounts entities.
type TwitterAccountsQuery struct {
	config
	ctx              *QueryContext
	order            []twitteraccounts.OrderOption
	inters           []Interceptor
	predicates       []predicate.TwitterAccounts
	withConversation *ConversationsQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TwitterAccountsQuery builder.
func (taq *TwitterAccountsQuery) Where(ps ...predicate.TwitterAccounts) *TwitterAccountsQuery {
	taq.predicates = append(taq.predicates, ps...)
	return taq
}

// Limit the number of records to be returned by this query.
func (taq *TwitterAccountsQuery) Limit(limit int) *TwitterAccountsQuery {
	taq.ctx.Limit = &limit
	return taq
}

// Offset to start from.
func (taq *TwitterAccountsQuery) Offset(offset int) *TwitterAccountsQuery {
	taq.ctx.Offset = &offset
	return taq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (taq *TwitterAccountsQuery) Unique(unique bool) *TwitterAccountsQuery {
	taq.ctx.Unique = &unique
	return taq
}

// Order specifies how the records should be ordered.
func (taq *TwitterAccountsQuery) Order(o ...twitteraccounts.OrderOption) *TwitterAccountsQuery {
	taq.order = append(taq.order, o...)
	return taq
}

// QueryConversation chains the current query on the "conversation" edge.
func (taq *TwitterAccountsQuery) QueryConversation() *ConversationsQuery {
	query := (&ConversationsClient{config: taq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := taq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := taq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(twitteraccounts.Table, twitteraccounts.FieldID, selector),
			sqlgraph.To(conversations.Table, conversations.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, twitteraccounts.ConversationTable, twitteraccounts.ConversationColumn),
		)
		fromU = sqlgraph.SetNeighbors(taq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TwitterAccounts entity from the query.
// Returns a *NotFoundError when no TwitterAccounts was found.
func (taq *TwitterAccountsQuery) First(ctx context.Context) (*TwitterAccounts, error) {
	nodes, err := taq.Limit(1).All(setContextOp(ctx, taq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{twitteraccounts.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (taq *TwitterAccountsQuery) FirstX(ctx context.Context) *TwitterAccounts {
	node, err := taq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TwitterAccounts ID from the query.
// Returns a *NotFoundError when no TwitterAccounts ID was found.
func (taq *TwitterAccountsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = taq.Limit(1).IDs(setContextOp(ctx, taq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{twitteraccounts.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (taq *TwitterAccountsQuery) FirstIDX(ctx context.Context) int {
	id, err := taq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TwitterAccounts entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TwitterAccounts entity is found.
// Returns a *NotFoundError when no TwitterAccounts entities are found.
func (taq *TwitterAccountsQuery) Only(ctx context.Context) (*TwitterAccounts, error) {
	nodes, err := taq.Limit(2).All(setContextOp(ctx, taq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{twitteraccounts.Label}
	default:
		return nil, &NotSingularError{twitteraccounts.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (taq *TwitterAccountsQuery) OnlyX(ctx context.Context) *TwitterAccounts {
	node, err := taq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TwitterAccounts ID in the query.
// Returns a *NotSingularError when more than one TwitterAccounts ID is found.
// Returns a *NotFoundError when no entities are found.
func (taq *TwitterAccountsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = taq.Limit(2).IDs(setContextOp(ctx, taq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{twitteraccounts.Label}
	default:
		err = &NotSingularError{twitteraccounts.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (taq *TwitterAccountsQuery) OnlyIDX(ctx context.Context) int {
	id, err := taq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TwitterAccountsSlice.
func (taq *TwitterAccountsQuery) All(ctx context.Context) ([]*TwitterAccounts, error) {
	ctx = setContextOp(ctx, taq.ctx, "All")
	if err := taq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TwitterAccounts, *TwitterAccountsQuery]()
	return withInterceptors[[]*TwitterAccounts](ctx, taq, qr, taq.inters)
}

// AllX is like All, but panics if an error occurs.
func (taq *TwitterAccountsQuery) AllX(ctx context.Context) []*TwitterAccounts {
	nodes, err := taq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TwitterAccounts IDs.
func (taq *TwitterAccountsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if taq.ctx.Unique == nil && taq.path != nil {
		taq.Unique(true)
	}
	ctx = setContextOp(ctx, taq.ctx, "IDs")
	if err = taq.Select(twitteraccounts.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (taq *TwitterAccountsQuery) IDsX(ctx context.Context) []int {
	ids, err := taq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (taq *TwitterAccountsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, taq.ctx, "Count")
	if err := taq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, taq, querierCount[*TwitterAccountsQuery](), taq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (taq *TwitterAccountsQuery) CountX(ctx context.Context) int {
	count, err := taq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (taq *TwitterAccountsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, taq.ctx, "Exist")
	switch _, err := taq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (taq *TwitterAccountsQuery) ExistX(ctx context.Context) bool {
	exist, err := taq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TwitterAccountsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (taq *TwitterAccountsQuery) Clone() *TwitterAccountsQuery {
	if taq == nil {
		return nil
	}
	return &TwitterAccountsQuery{
		config:           taq.config,
		ctx:              taq.ctx.Clone(),
		order:            append([]twitteraccounts.OrderOption{}, taq.order...),
		inters:           append([]Interceptor{}, taq.inters...),
		predicates:       append([]predicate.TwitterAccounts{}, taq.predicates...),
		withConversation: taq.withConversation.Clone(),
		// clone intermediate query.
		sql:  taq.sql.Clone(),
		path: taq.path,
	}
}

// WithConversation tells the query-builder to eager-load the nodes that are connected to
// the "conversation" edge. The optional arguments are used to configure the query builder of the edge.
func (taq *TwitterAccountsQuery) WithConversation(opts ...func(*ConversationsQuery)) *TwitterAccountsQuery {
	query := (&ConversationsClient{config: taq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	taq.withConversation = query
	return taq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TwitterAccountID string `json:"twitter_account_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TwitterAccounts.Query().
//		GroupBy(twitteraccounts.FieldTwitterAccountID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (taq *TwitterAccountsQuery) GroupBy(field string, fields ...string) *TwitterAccountsGroupBy {
	taq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TwitterAccountsGroupBy{build: taq}
	grbuild.flds = &taq.ctx.Fields
	grbuild.label = twitteraccounts.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TwitterAccountID string `json:"twitter_account_id,omitempty"`
//	}
//
//	client.TwitterAccounts.Query().
//		Select(twitteraccounts.FieldTwitterAccountID).
//		Scan(ctx, &v)
func (taq *TwitterAccountsQuery) Select(fields ...string) *TwitterAccountsSelect {
	taq.ctx.Fields = append(taq.ctx.Fields, fields...)
	sbuild := &TwitterAccountsSelect{TwitterAccountsQuery: taq}
	sbuild.label = twitteraccounts.Label
	sbuild.flds, sbuild.scan = &taq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TwitterAccountsSelect configured with the given aggregations.
func (taq *TwitterAccountsQuery) Aggregate(fns ...AggregateFunc) *TwitterAccountsSelect {
	return taq.Select().Aggregate(fns...)
}

func (taq *TwitterAccountsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range taq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, taq); err != nil {
				return err
			}
		}
	}
	for _, f := range taq.ctx.Fields {
		if !twitteraccounts.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if taq.path != nil {
		prev, err := taq.path(ctx)
		if err != nil {
			return err
		}
		taq.sql = prev
	}
	return nil
}

func (taq *TwitterAccountsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TwitterAccounts, error) {
	var (
		nodes       = []*TwitterAccounts{}
		withFKs     = taq.withFKs
		_spec       = taq.querySpec()
		loadedTypes = [1]bool{
			taq.withConversation != nil,
		}
	)
	if taq.withConversation != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, twitteraccounts.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TwitterAccounts).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TwitterAccounts{config: taq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, taq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := taq.withConversation; query != nil {
		if err := taq.loadConversation(ctx, query, nodes, nil,
			func(n *TwitterAccounts, e *Conversations) { n.Edges.Conversation = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (taq *TwitterAccountsQuery) loadConversation(ctx context.Context, query *ConversationsQuery, nodes []*TwitterAccounts, init func(*TwitterAccounts), assign func(*TwitterAccounts, *Conversations)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*TwitterAccounts)
	for i := range nodes {
		if nodes[i].twitter_accounts_conversation == nil {
			continue
		}
		fk := *nodes[i].twitter_accounts_conversation
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(conversations.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "twitter_accounts_conversation" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (taq *TwitterAccountsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := taq.querySpec()
	_spec.Node.Columns = taq.ctx.Fields
	if len(taq.ctx.Fields) > 0 {
		_spec.Unique = taq.ctx.Unique != nil && *taq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, taq.driver, _spec)
}

func (taq *TwitterAccountsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(twitteraccounts.Table, twitteraccounts.Columns, sqlgraph.NewFieldSpec(twitteraccounts.FieldID, field.TypeInt))
	_spec.From = taq.sql
	if unique := taq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if taq.path != nil {
		_spec.Unique = true
	}
	if fields := taq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, twitteraccounts.FieldID)
		for i := range fields {
			if fields[i] != twitteraccounts.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := taq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := taq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := taq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := taq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (taq *TwitterAccountsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(taq.driver.Dialect())
	t1 := builder.Table(twitteraccounts.Table)
	columns := taq.ctx.Fields
	if len(columns) == 0 {
		columns = twitteraccounts.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if taq.sql != nil {
		selector = taq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if taq.ctx.Unique != nil && *taq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range taq.predicates {
		p(selector)
	}
	for _, p := range taq.order {
		p(selector)
	}
	if offset := taq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := taq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TwitterAccountsGroupBy is the group-by builder for TwitterAccounts entities.
type TwitterAccountsGroupBy struct {
	selector
	build *TwitterAccountsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tagb *TwitterAccountsGroupBy) Aggregate(fns ...AggregateFunc) *TwitterAccountsGroupBy {
	tagb.fns = append(tagb.fns, fns...)
	return tagb
}

// Scan applies the selector query and scans the result into the given value.
func (tagb *TwitterAccountsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tagb.build.ctx, "GroupBy")
	if err := tagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TwitterAccountsQuery, *TwitterAccountsGroupBy](ctx, tagb.build, tagb, tagb.build.inters, v)
}

func (tagb *TwitterAccountsGroupBy) sqlScan(ctx context.Context, root *TwitterAccountsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tagb.fns))
	for _, fn := range tagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tagb.flds)+len(tagb.fns))
		for _, f := range *tagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TwitterAccountsSelect is the builder for selecting fields of TwitterAccounts entities.
type TwitterAccountsSelect struct {
	*TwitterAccountsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tas *TwitterAccountsSelect) Aggregate(fns ...AggregateFunc) *TwitterAccountsSelect {
	tas.fns = append(tas.fns, fns...)
	return tas
}

// Scan applies the selector query and scans the result into the given value.
func (tas *TwitterAccountsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tas.ctx, "Select")
	if err := tas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TwitterAccountsQuery, *TwitterAccountsSelect](ctx, tas.TwitterAccountsQuery, tas, tas.inters, v)
}

func (tas *TwitterAccountsSelect) sqlScan(ctx context.Context, root *TwitterAccountsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tas.fns))
	for _, fn := range tas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
