version: '3'

services:
  controller:
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile.controller
    ports:
      - 8080:8080
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app
    environment:
      POSTGRES_HOST: postgresql
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
      CLOUDTASKS_HOST: gcloud-tasks-emulator
      CLOUDTASKS_PARENT: projects/dev/locations/here
  gcloud-tasks-emulator:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: -host 0.0.0.0 -port 8123 -queue "projects/dev/locations/here/queues/anotherq"
    ports:
      - "${TASKS_PORT:-8123}:8123"
  postgresql:
    image: postgres:14.0-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db