-- +goose Up
-- create "twitter_accounts" table
CREATE TABLE "twitter_accounts" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "twitter_account_id" character varying NOT NULL, "bearer_token" character varying NOT NULL, "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("id"));
-- create "conversations" table
CREATE TABLE "conversations" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "ai_model" character varying NOT NULL, "sns_type" character varying NOT NULL, "cmd_version" character varying NOT NULL, "is_aborted" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, "twitter_accounts_conversation" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "conversations_twitter_accounts_conversation" FOREIGN KEY ("twitter_accounts_conversation") REFERENCES "twitter_accounts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- create index "conversations_twitter_accounts_conversation_key" to table: "conversations"
CREATE UNIQUE INDEX "conversations_twitter_accounts_conversation_key" ON "conversations" ("twitter_accounts_conversation");

-- +goose Down
-- reverse: create index "conversations_twitter_accounts_conversation_key" to table: "conversations"
DROP INDEX "conversations_twitter_accounts_conversation_key";
-- reverse: create "conversations" table
DROP TABLE "conversations";
-- reverse: create "twitter_accounts" table
DROP TABLE "twitter_accounts";
